### PR TITLE
Switch to Financial Modeling Prep API

### LINKED ISSUE #19: markitondemand API no longer working
The site dev.markitondemand.com that provided stock data for this Mycroft skill is no longer functioning.  Therefore the Mycroft skill fails.

### PR DESCRIPTION
**Pull request by forslund**
This should restore functionality of the skill and resolve #19.

### CODE REVIEW

**Review by krisgesling — COMMENTED** [review]
Looks good. 

Should we be catching http errors in the event the API goes down or something?

**Comment by forslund** [comment]
Might be a good addition. I'll add something like it

**Comment by forslund** [comment]
I added handling for bad HTTP statuses.

**Comment by krisgesling** [comment]
Great, thanks!

**Pull request merged**
